In [62]:
import numpy as np

In [63]:
def Viterbi(O, A, B, pi):
    """Viterbi aims to find the best road leading to observe, given A, B, pi

    Args:
        O ([list]): contains observed sequence
        A ([matrix]): aij for prob that convert from status i at time-step t to status j at time-step t+1
        B ([matrix]): bij for at time-step t, status i yields observe output j
        pi ([ndarray]): PIi for prob of status i serves as initial status
    
    Returns:
        [float]: probability of the best road
        [ndarray]: index of node of the best road at each time-step
    """
    N = A.shape[0]
    T = len(O)
    Sigma = np.zeros((N, T))            ## Sigma(i, j) - the biggest probability of status i at t.s. t with o1, o2, ..., ot
    Psi = np.zeros((N, T))              ## Psi(i, j) - the node at t.s. t-1 of  the best road
    I = np.zeros(T)

    Sigma[:, 0] = pi * B[:, O[0]]
    Psi[:, 0] = 0
    
    for t in range(T - 1):
        Sigma[:, t + 1] = np.max(Sigma[:, t].reshape(3, 1) * A, axis = 0) * B[:, O[t + 1]]
        Psi[:, t + 1] = np.argmax(Sigma[:, t].reshape(3, 1) * A, axis = 0)
    best_P = np.max(Sigma[:, -1])
    I[-1] = np.argmax(Sigma[:, -1])

    for t in reversed(range(T - 1)):
        I[t] = Psi[int(I[t + 1]), t + 1]

    return best_P, I


In [64]:
A = np.array([[0.5, 0.2, 0.3],
              [0.3, 0.5, 0.2],
              [0.2, 0.3, 0.5]])

B = np.array([[0.5, 0.5],
              [0.4, 0.6],
              [0.7, 0.3]])

pi = np.array([[0.2, 0.4, 0.4]])
O = [0, 1, 0, 1]

In [65]:
best_P, I = Viterbi(O, A, B, pi)
print(best_P)
print(I)

0.0030239999999999993
[2. 1. 1. 1.]


In [68]:
sigma = np.array([[0.1 , 0.  , 0.  , 0.  ],
       [0.16, 0.  , 0.  , 0.  ],
       [0.28, 0.  , 0.  , 0.  ]])
A = np.array([[0.5, 0.2, 0.3],
              [0.3, 0.5, 0.2],
              [0.2, 0.3, 0.5]])
print(sigma[:, 0])
print("slice shape:", sigma[:, 0].shape)
print(sigma[:, 0].reshape(3, 1))
print("after reshape:", sigma[:, 0].reshape(3, 1).shape)
print("No reshape multiply: ", sigma[:, 0] * A)
print("After reshape multiply: ", sigma[:, 0].reshape(3, 1) * A)
print(np.max(sigma[:, 0].reshape(3, 1) * A, axis=0))

[0.1  0.16 0.28]
slice shape: (3,)
[[0.1 ]
 [0.16]
 [0.28]]
after reshape: (3, 1)
No reshape multiply:  [[0.05  0.032 0.084]
 [0.03  0.08  0.056]
 [0.02  0.048 0.14 ]]
After reshape multiply:  [[0.05  0.02  0.03 ]
 [0.048 0.08  0.032]
 [0.056 0.084 0.14 ]]
[0.056 0.084 0.14 ]
